name: ClipCourt
options:
  bundleIdPrefix: com.clipcourt
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: false

targets:
  ClipCourt:
    type: application
    platform: iOS
    sources:
      - path: ClipCourt
        excludes:
          - "**/*.md"
    settings:
      base:
        INFOPLIST_FILE: ClipCourt/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.clipcourt.app
        PRODUCT_NAME: ClipCourt
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""


  ClipCourtTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ClipCourtTests
    settings:
      base:
        INFOPLIST_FILE: ClipCourtTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.clipcourt.tests
        SWIFT_VERSION: "5.9"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ClipCourt.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/ClipCourt"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: false
    dependencies:
      - target: ClipCourt

schemes:
  ClipCourt:
    build:
      targets:
        ClipCourt: all
        ClipCourtTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ClipCourtTests
