name: ClipCourt
options:
  bundleIdPrefix: com.clipcourt
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: false

targets:
  ClipCourt:
    type: application
    platform: iOS
    sources:
      - path: ClipCourt
        excludes:
          - "**/*.md"
    settings:
      base:
        INFOPLIST_FILE: ClipCourt/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.clipcourt.app
        PRODUCT_NAME: ClipCourt
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""


schemes:
  ClipCourt:
    build:
      targets:
        ClipCourt: all
    run:
      config: Debug
